### ISSUE TITLE
Using default import in an ESM project results in an error

### ISSUE THREAD

**Issue by mryechkin** [Ephem/rollup-plugin-preserve-directives#1]
When running a project as ESM (either by having `"type": "module"` in `package.json` or using `.mjs` extension for Rollup config, see [docs](https://rollupjs.org/migration/#using-configuration-files) for more info), using a default import of this plugin results in an error:

![Screenshot 2023-03-14 at 3 09 02 PM](https://user-images.githubusercontent.com/5657181/225112651-f710d9a5-cd69-45b0-a249-09308d33c7dc.png)

Changing `preserveDirectives()` to `preserveDirectives.default()` fixes this issue:

```js
// rollup.config.mjs
import preserveDirectives from "rollup-plugin-preserve-directives";

export default {
  output: {
    preserveModules: true,
  },
  plugins: [preserveDirectives.default()],
};
```

I believe this is due to how TypeScript bundles the library code when the [esModuleInterop](https://www.typescriptlang.org/tsconfig#esModuleInterop) option is set (as is the case in that plugin):

![Screenshot 2023-03-14 at 3 09 20 PM](https://user-images.githubusercontent.com/5657181/225112562-bb80fc35-e8ec-42fe-bbd7-d48207e8ceb7.png)

I'm not familiar with how TS compiles the final bundle, but I believe that changing to named exports will fix this issue, and make it work the same in both CommonJS and ESM.

**Comment by PunkFleet** [comment]
TS2339: Property 'default' does not exist on type '({ supressPreserveModulesWarning, }?: PreserveDirectivesOptions) => Plugin'.
