### ISSUE TITLE
Exclude / include functionality

### ISSUE THREAD

**Issue by samevision** [Ephem/rollup-plugin-preserve-directives#2]
Hi,

I am very happy that this plugin was released just now. I had problems bundling NextJs 13 client components due to the 'use client' before.

Unfortunately I can't decide what should be preserved and what shouldn't. I importing @headlessui/react leads to problems since it uses:

`import "client-only";`

The following error appears:
`[!] (plugin commonjs--resolver) TypeError: Cannot read properties of undefined (reading 'type')`

How can we avoid this?

Best

**Comment by Ephem** [comment]
Hi, glad you think so!

I'd love some more context to try to understand this. Are you bundling a library/some components you want to be usable directly from React Server components? From where are you importing `@headlessui/react`? From a Server Component or one that has `'use client'` at the top?

**Comment by Ephem** [comment]
I think this was the same issue reported in #5 which was fixed by #6 and released in `0.1.1`. Hopefully that fixes it for you too?
