### ISSUE TITLE
Error running plugin hook renderChunk for preserve-directives

### ISSUE THREAD

**Issue by vivekgupta5** [Ephem/rollup-plugin-preserve-directives#25]
rollup: v2.26.9
rollup-plugin-preserve-directives: v0.4.0

Hi team, 
I am trying to use this plugin to preserve 'use client' directive, but when I add this plugin I am getting the below error.

Getting a below error while trying to build esm and cjs:
```
[esm] [!] (plugin preserve-directives) Error: Error running plugin hook renderChunk for preserve-directives, expected a function hook.
[esm] Error: Error running plugin hook renderChunk for preserve-directives, expected a function hook.
```

```
[cjs] [!] (plugin preserve-directives) Error: Error running plugin hook renderChunk for preserve-directives, expected a function hook.
[cjs] Error: Error running plugin hook renderChunk for preserve-directives, expected a function hook.
```

**Comment by Ephem** [comment]
I was going through some old issues and came across this, sorry for not responding sooner. Closing as duplicate of https://github.com/Ephem/rollup-plugin-preserve-directives/issues/8

I just commented over there, but pretty much, I don't think this plugin supports v2 so I'll go ahead and remove it from the peerDependency array to indicate as much.
