### ISSUE TITLE
[!] Error: rollup-plugin-preserve-directives tried to access magic-string, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

### ISSUE THREAD

**Issue by georgebutter** [Ephem/rollup-plugin-preserve-directives#4]
I think magic-string should be in the regular dependencies (not dev) but I'm not sure.

**Comment by Ephem** [comment]
Oh look at that, nice catch! I verified official Rollup plugins were indeed doing it that way and it's now moved over to a dependency in `0.1.1`, thanks for reporting it.
